### ISSUE TITLE
New 1.X.X Release

### ISSUE THREAD

**Issue by trevorriles** [seancribbs/neotoma#37]
Hi Sean, I noticed the 1.7.2 release doesn't parse unicode characters correctly on E18. After switching to the master branch I have no issues.

I am testing with [basho/cuttlefish](https://github.com/basho/cuttlefish) and neotoma, on master neotoma uses `unicode:characters _to_binary` instead of `list_to_binary` which solves the problem.

Making this issue because I like to avoid locking to a master branch.

**Comment by seancribbs** [comment]
I've been sporadically working on a rewrite of the entire thing but this deserves a tag. Sorry for the delay.

**Comment by seancribbs** [comment]
Tagged https://github.com/seancribbs/neotoma/releases/tag/1.7.3

**Comment by macintux** [comment]
Thanks @seancribbs
